In [1]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("../quality_data/Sleep_health_and_lifestyle_dataset.csv")

# 앞부분 확인
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [2]:
# 데이터 크기 확인
df.shape

(374, 13)

In [3]:
# 데이터 정보 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    str
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    str
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    str
 9   Blood Pressure           374 non-null    str
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 49.2 KB

In [4]:
# 결측치 확인
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [5]:
# 중복 데이터 확인
df.duplicated().sum()

np.int64(0)

In [6]:
# 수면장애 종류와 개수 확인
df["Sleep Disorder"].value_counts(dropna=False)

Sleep Disorder
NaN            219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [7]:
# 수면장애 결측치는 'None'으로 변경
df["Sleep Disorder"] = df["Sleep Disorder"].fillna("None")

In [8]:
df["Sleep Disorder"].value_counts()

Sleep Disorder
None           219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [9]:
# Person ID 제거
df = df.drop("Person ID", axis=1)

# 컬럼 확인
df.columns

Index(['Gender', 'Age', 'Occupation', 'Sleep Duration', 'Quality of Sleep',
       'Physical Activity Level', 'Stress Level', 'BMI Category',
       'Blood Pressure', 'Heart Rate', 'Daily Steps', 'Sleep Disorder'],
      dtype='str')

In [10]:
# BMI Category 종류 확인
df["BMI Category"].value_counts()

BMI Category
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64

In [11]:
# BMI Category 값 통일
df["BMI Category"] = df["BMI Category"].replace("Normal Weight", "Normal")

# 변경 결과 확인
df["BMI Category"].value_counts()

BMI Category
Normal        216
Overweight    148
Obese          10
Name: count, dtype: int64

In [12]:
# Blood Pressure 값 확인
df["Blood Pressure"].head(10)

0    126/83
1    125/80
2    125/80
3    140/90
4    140/90
5    140/90
6    140/90
7    120/80
8    120/80
9    120/80
Name: Blood Pressure, dtype: str

In [13]:
# Blood Pressure를 수축기/이완기 혈압으로 분리
df[["Systolic BP", "Diastolic BP"]] = df["Blood Pressure"].str.split("/", expand=True)

# 숫자형으로 변환
df["Systolic BP"] = df["Systolic BP"].astype(int)
df["Diastolic BP"] = df["Diastolic BP"].astype(int)

# 결과 확인
df[["Blood Pressure", "Systolic BP", "Diastolic BP"]].head()

  Blood Pressure  Systolic BP  Diastolic BP
0         126/83          126            83
1         125/80          125            80
2         125/80          125            80
3         140/90          140            90
4         140/90          140            90

In [14]:
# 기존 Blood Pressure 컬럼 제거
df = df.drop("Blood Pressure", axis=1)

# 현재 컬럼 확인
df.columns

Index(['Gender', 'Age', 'Occupation', 'Sleep Duration', 'Quality of Sleep',
       'Physical Activity Level', 'Stress Level', 'BMI Category', 'Heart Rate',
       'Daily Steps', 'Sleep Disorder', 'Systolic BP', 'Diastolic BP'],
      dtype='str')

In [15]:
# 문자형 컬럼 확인
df.select_dtypes(include="object").columns

/var/folders/dr/kvqr_k0j3sx48xxkm9xg0mn80000gn/T/ipykernel_19194/1165379035.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['Gender', 'Occupation', 'BMI Category', 'Sleep Disorder'], dtype='str')

In [16]:
# 문자형 컬럼 값 확인
print("Gender")
print(df["Gender"].value_counts())

print("\nOccupation")
print(df["Occupation"].value_counts())

print("\nBMI Category")
print(df["BMI Category"].value_counts())

print("\nSleep Disorder")
print(df["Sleep Disorder"].value_counts())

Gender
Gender
Male      189
Female    185
Name: count, dtype: int64

Occupation
Occupation
Nurse                   73
Doctor                  71
Engineer                63
Lawyer                  47
Teacher                 40
Accountant              37
Salesperson             32
Software Engineer        4
Scientist                4
Sales Representative     2
Manager                  1
Name: count, dtype: int64

BMI Category
BMI Category
Normal        216
Overweight    148
Obese          10
Name: count, dtype: int64

Sleep Disorder
Sleep Disorder
None           219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [17]:
# 활동 수준 확인
df["Physical Activity Level"].describe()

count    374.000000
mean      59.171123
std       20.830804
min       30.000000
25%       45.000000
50%       60.000000
75%       75.000000
max       90.000000
Name: Physical Activity Level, dtype: float64

In [18]:
sorted(df["Physical Activity Level"].unique())

[np.int64(30),
 np.int64(32),
 np.int64(35),
 np.int64(40),
 np.int64(42),
 np.int64(45),
 np.int64(47),
 np.int64(50),
 np.int64(55),
 np.int64(60),
 np.int64(65),
 np.int64(70),
 np.int64(75),
 np.int64(80),
 np.int64(85),
 np.int64(90)]

In [19]:
# 전처리 결과 확인
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic BP,Diastolic BP
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,None,126,83
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125,80
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125,80
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90

In [20]:
# 최종 데이터 정보 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   374 non-null    str
 1   Age                      374 non-null    int64
 2   Occupation               374 non-null    str
 3   Sleep Duration           374 non-null    float64
 4   Quality of Sleep         374 non-null    int64
 5   Physical Activity Level  374 non-null    int64
 6   Stress Level             374 non-null    int64
 7   BMI Category             374 non-null    str
 8   Heart Rate               374 non-null    int64
 9   Daily Steps              374 non-null    int64
 10  Sleep Disorder           374 non-null    str
 11  Systolic BP              374 non-null    int64
 12  Diastolic BP             374 non-null    int64
dtypes: float64(1), int64(8), str(4)
memory usage: 47.7 KB

In [21]:
# 전처리된 데이터 저장
df.to_csv("../quality_data/quality_prep.csv", index=False)

print("전처리 완료")

전처리 완료

In [22]:
# ============================================
# 모델링을 위한 추가 전처리
# ============================================

# 입력 데이터(X)와 예측 대상(y) 분리
X = df.drop(columns=["Quality of Sleep", "Sleep Disorder"])
y = df["Quality of Sleep"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nQuality of Sleep 값:")
print(y.value_counts().sort_index())

X shape: (374, 11)
y shape: (374,)

Quality of Sleep 값:
Quality of Sleep
4      5
5      7
6    105
7     77
8    109
9     71
Name: count, dtype: int64

In [23]:
# Quality of Sleep 점수를 3단계로 범주화
def sleep_quality_group(score):
    if score <= 5:
        return "Low"
    elif score <= 7:
        return "Medium"
    else:
        return "High"

y = df["Quality of Sleep"].apply(sleep_quality_group)

# 범주별 개수 확인
print(y.value_counts())

Quality of Sleep
Medium    182
High      180
Low        12
Name: count, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

# 학습용 데이터와 테스트용 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 데이터 크기 확인
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

# 분류 비율 확인
print("\n학습 데이터:")
print(y_train.value_counts())

print("\n테스트 데이터:")
print(y_test.value_counts())

X_train: (299, 11)
X_test: (75, 11)
y_train: (299,)
y_test: (75,)

학습 데이터:
Quality of Sleep
Medium    145
High      144
Low        10
Name: count, dtype: int64

테스트 데이터:
Quality of Sleep
Medium    37
High      36
Low        2
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# 숫자형 컬럼
numeric_columns = X_train.select_dtypes(exclude="object").columns

# 범주형 컬럼
categorical_columns = X_train.select_dtypes(include="object").columns

print("숫자형 컬럼:")
print(list(numeric_columns))

print("\n범주형 컬럼:")
print(list(categorical_columns))

숫자형 컬럼:
['Age', 'Sleep Duration', 'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps', 'Systolic BP', 'Diastolic BP']

범주형 컬럼:
['Gender', 'Occupation', 'BMI Category']

/var/folders/dr/kvqr_k0j3sx48xxkm9xg0mn80000gn/T/ipykernel_19194/3454061375.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(include="object").columns

In [26]:
# 스케일링 + 원핫인코딩 설정
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_columns)
    ]
)

# 학습 데이터 기준으로 전처리
X_train_processed = preprocessor.fit_transform(X_train)

# 테스트 데이터는 학습 데이터 기준으로 변환
X_test_processed = preprocessor.transform(X_test)

# 결과 크기 확인
print("X_train_processed:", X_train_processed.shape)
print("X_test_processed:", X_test_processed.shape)

X_train_processed: (299, 24)
X_test_processed: (75, 24)

In [27]:
import pickle

# 전처리 결과 pkl 파일로 저장
data = {
    "X_train": X_train_processed,
    "X_test": X_test_processed,
    "y_train": y_train,
    "y_test": y_test,
    "preprocessor": preprocessor
}

with open("../quality_data/quality_prep.pkl", "wb") as f:
    pickle.dump(data, f)

print("pkl 파일 저장 완료")

pkl 파일 저장 완료

In [28]:
# 저장한 pkl 파일 확인
with open("../quality_data/quality_prep.pkl", "rb") as f:
    check_data = pickle.load(f)

print(check_data.keys())
print("X_train:", check_data["X_train"].shape)
print("X_test:", check_data["X_test"].shape)
print("y_train:", check_data["y_train"].shape)
print("y_test:", check_data["y_test"].shape)

dict_keys(['X_train', 'X_test', 'y_train', 'y_test', 'preprocessor'])
X_train: (299, 24)
X_test: (75, 24)
y_train: (299,)
y_test: (75,)